### ISSUE TITLE
F2 Wapens afgeven

### ISSUE THREAD

**Issue by fluffyxs** [UniitedRP/development#11]
**Omschrijf de bug**

Kan geen wapens afgeven met F2 

**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**

Geen idee

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**

Dat het wapen word afgegeven

**Screenshot/video en of logbestanden**

Heb ik hier niet van

**Impact voor de server**

Best wel en impact invb met veel scenario's komen wapens in voor

**Comment by Cryonite** [comment]
Wordt naar gekeken

**Comment by Me-KO** [comment]
Is gefixt
