### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by JoqUnited** [UniitedRP/development#12]
**Omschrijf de bug**
politie en ANWB staan samen op het scoreboard maar dat is beetje vervelend voor de burgers ook want zij weten nu niet hoeveel politie er is en andersom
**Hoe kunnen wij de bug reproduceren (welke stappen moeten wij maken om dit ook te krijgen)**
geen idee

**Normaal gedrag (Wat zou er normaal moeten gebeuren)**
Je zou het apart moeten zien staan 

**Screenshot/video en of logbestanden**
![image](https://user-images.githubusercontent.com/84094808/118047259-ceb0b000-b37a-11eb-8596-f7fc6554288f.png)
er staat altijd geen ANWB online

**Impact voor de server**
RP word een beetje verminderd met de politie

**Comment by Cryonite** [comment]
gefixed
